name: Build Test and Build Push Docker Image Operator

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
env:
  DEFAULT_JDK_VERSION: 17
  DEFAULT_JDK_DIST: temurin
  MINIKUBE_VERSION: v1.28.0
  KUBERNETES_VERSION: v1.22.3

defaults:
  run:
    shell: bash

concurrency:
  # Only cancel jobs for PR updates
  group: operator-ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.7
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package -P operator -DskipTests=true -pl operator -am  
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ secrets.RP_Registry_URL }}
          username: ${{ secrets.RP_Registry_User }}
          password: ${{ secrets.RP_Registry_Password }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: operator/Dockerfile
          push: true
          tags: |
            ${{ secrets.RP_Registry_URL }}/keycloak/keycloak-operator:latest
            ${{ secrets.RP_Registry_URL }}/keycloak/keycloak-operator:${{ github.sha }}
